[workspace]
members = [
    "crates/secret-sharing-cli",
    "crates/crypto",
    "crates/crypto-wasm",
    "crates/encodings/text-utf8-v1",
    "crates/gadgets",
    "crates/circuits",
    "crates/prover",
    "crates/prover-server",
    "crates/prover-wasm",
    "crates/protocol",
]
resolver = "3"
