//! Curve-level operations on Baby Jubjub points.
//!
//! Thin, intention-revealing wrappers over the arkworks group arithmetic that
//! `BabyJubConfig` already provides. The point of this file is *naming and
//! safety checks*, not reimplementing elliptic-curve math: arkworks does
//! add/double/scalar-mul; we give those operations protocol-meaningful names
//! and add the predicate checks (`is_on_curve`, `is_in_prime_subgroup`) that
//! callers need before trusting an externally-supplied point.

use ark_ec::{twisted_edwards::TECurveConfig, CurveGroup};

use super::config::{BabyJubConfig, EdwardsAffine, EdwardsProjective, Fr};

/// The group identity (neutral element): `(0, 1)` in twisted Edwards
/// coordinates. Adding it to any point returns that point unchanged.
pub const IDENTITY: EdwardsAffine = EdwardsAffine::new_unchecked(
    ark_ff::MontFp!("0"),
    ark_ff::MontFp!("1"),
);

/// The conventional generator: circomlib's `Base8`. Every public key is a
/// scalar multiple of this point, so two implementations only interoperate if
/// they agree on it — which is the whole reason `config.rs` pins the ERC-2494
/// dialect.
pub fn generator() -> EdwardsAffine {
    BabyJubConfig::GENERATOR
}

/// Scalar multiplication: `scalar · point`.
///
/// This is the workhorse — `keypair` will call it as `sk · G`, ECDH will call
/// it as `sk · their_pubkey`. Takes an affine point for an ergonomic call site,
/// returns affine so the result has canonical coordinates ready to serialize.
/// Internally arkworks does the multiply in projective coordinates.
pub fn mul(scalar: &Fr, point: &EdwardsAffine) -> EdwardsAffine {
    // `mul_bigint` would also work, but `*` on the projective point goes
    // through the same constant-time-ish double-and-add and keeps the call
    // readable.
    (EdwardsProjective::from(*point) * scalar).into_affine()
}

/// Does `point` actually satisfy the Baby Jubjub curve equation
/// `a·x² + y² = 1 + d·x²·y²`?
///
/// arkworks' `is_on_curve` reads the curve parameters straight from
/// `BabyJubConfig`, so this is automatically checking against the ERC-2494
/// `a`/`d` — not some other curve. Always run this on a point that arrived
/// from outside the process (a wire-decoded public key, say) before doing
/// anything cryptographic with it.
pub fn is_on_curve(point: &EdwardsAffine) -> bool {
    point.is_on_curve()
}

/// Is `point` in the prime-order subgroup generated by `Base8`?
///
/// On-curve is necessary but not sufficient: the full curve has order `8·l`,
/// and a point in one of the small-order components can enable subgroup-
/// confinement attacks. A public key the protocol accepts must be on-curve
/// *and* in the prime subgroup. arkworks checks this as `l · point == identity`.
pub fn is_in_prime_subgroup(point: &EdwardsAffine) -> bool {
    point.is_in_correct_subgroup_assuming_on_curve()
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_ec::PrimeGroup;
    use ark_ff::{AdditiveGroup, Field, PrimeField};
    use ark_std::UniformRand;

    /// `Base8` — the constant we transcribed into `config.rs` — must itself be
    /// a valid curve point. If `a`, `d`, or the generator coordinates were
    /// mistyped, this fails immediately.
    #[test]
    fn generator_is_on_curve() {
        assert!(is_on_curve(&generator()));
    }

    /// `Base8` must be in the prime-order subgroup (that is the entire reason
    /// circomlib uses it rather than the cofactored generator `G`). If this
    /// holds, every `sk · G` public key is also in the subgroup for free.
    #[test]
    fn generator_is_in_prime_subgroup() {
        assert!(is_in_prime_subgroup(&generator()));
    }

    /// Sanity on the group law: `0 · G` is the identity, `1 · G` is `G`.
    #[test]
    fn scalar_mul_edge_scalars() {
        assert_eq!(mul(&Fr::ZERO, &generator()), IDENTITY);
        assert_eq!(mul(&Fr::ONE, &generator()), generator());
    }

    /// Scalar multiplication must be a group homomorphism in the scalar:
    /// `(a + b) · G == a·G + b·G`. This catches a wrong subgroup order (`Fr`
    /// modulus) — arithmetic mod the wrong `l` would break this identity.
    #[test]
    fn scalar_mul_is_additive() {
        let mut rng = ark_std::test_rng();
        let a = Fr::rand(&mut rng);
        let b = Fr::rand(&mut rng);
        let g = generator();

        let lhs = mul(&(a + b), &g);
        let rhs = (EdwardsProjective::from(mul(&a, &g)) + EdwardsProjective::from(mul(&b, &g)))
            .into_affine();
        assert_eq!(lhs, rhs);
    }

    /// The subgroup order `l` annihilates the generator: `l · G == identity`.
    /// This pins down that `Fr`'s modulus really is the Baby Jubjub subgroup
    /// order and not, say, the base field prime.
    #[test]
    fn subgroup_order_annihilates_generator() {
        // `Fr::MODULUS` is `l`. Reducing it into `Fr` gives 0, so multiply via
        // the integer bigint instead to actually compute `l · G`.
        let l = Fr::MODULUS;
        let prod = (EdwardsProjective::from(generator()).mul_bigint(l)).into_affine();
        assert_eq!(prod, IDENTITY);
    }
}
