//! Groth16 trusted setup, prove, and verify for the protocol's
//! circuits.
//!
//! ## What this crate is
//!
//! The thin wrapper around `ark-groth16` that pins the curve
//! (BN254) and the keypair-management discipline. Each circuit
//! in `crates/circuits` flows through three APIs here:
//!
//! - [`setup`] — run trusted setup on an `empty()` circuit
//!   instance, returning a `(ProvingKey, VerifyingKey)` pair.
//!   Persistent artifacts; in production, generated once by a
//!   ceremony and reused across all proofs for that circuit.
//! - [`prove`] — generate a Groth16 proof for a populated circuit
//!   instance, given its proving key.
//! - [`verify`] — check a proof against its verifying key and the
//!   public inputs declared by the circuit.
//!
//! ## Pinned in `specs/zk/stack.md`
//!
//! - **Groth16 on BN254** — Sui's native verifier.
//! - **PK / VK are deployment artifacts**, not source-controlled.
//!   This crate exposes serialize / deserialize helpers; the
//!   future `prover-server` writes them to disk on first boot.
//! - **No `tracing_subscriber` in the hot path.** A documented
//!   400× regression with Rayon's work-stealing scheduler. This
//!   crate does NOT install a tracing subscriber and the
//!   `Cargo.toml` deliberately does not depend on
//!   `tracing-subscriber`. Other crates in the workspace are
//!   free to use `tracing`; the prover is exempt.
//! - **Setup randomness.** Dev path uses `ark_std::test_rng` —
//!   deterministic, reproducible, suitable for local iteration
//!   and CI. Production deployments will need a ceremony spec
//!   (Powers of Tau or equivalent); that's a future doc.
//!
//! ## What this crate is NOT
//!
//! - **Not a server.** No HTTP surface, no I/O. The future
//!   `crates/prover-server` (Axum-based) wraps this crate.
//! - **Not WASM-bound.** No `wasm-bindgen` dependency. A future
//!   `crates/prover-wasm` will wrap this crate for in-browser
//!   proving — deliberately deferred (see the stack spec for
//!   the cost/benefit case).

use ark_bn254::{Bn254, Fr as Bn254Fr};
use ark_ff::{BigInteger, PrimeField};
use ark_groth16::{Groth16, PreparedVerifyingKey, Proof, ProvingKey, VerifyingKey};
use ark_relations::r1cs::ConstraintSynthesizer;
use ark_serialize::CanonicalDeserialize;
use ark_serialize::CanonicalSerialize;
use ark_snark::SNARK;
use ark_std::rand::{CryptoRng, RngCore};

use crypto::babyjub::Fq;

/// A Groth16 proving key for circuits over BN254. Generated by
/// [`setup`]; persisted as a byte blob between sessions.
pub type CircuitProvingKey = ProvingKey<Bn254>;

/// A Groth16 verifying key for circuits over BN254. The companion
/// to a `CircuitProvingKey`; the small artifact deployed to chain
/// (or to a verifier service).
pub type CircuitVerifyingKey = VerifyingKey<Bn254>;

/// A Groth16 proof. Three group elements; the entire encrypted
/// claim is in here plus the public inputs.
pub type CircuitProof = Proof<Bn254>;

/// Errors the prover can surface. Most failure modes (out-of-gas,
/// I/O) live in `prover-server`; this crate's failures are pure
/// math / synthesis errors and serialization failures.
#[derive(Debug, thiserror::Error)]
pub enum ProverError {
    /// The constraint system construction failed during setup,
    /// prove, or verify. The wrapped error carries arkworks'
    /// diagnostic.
    #[error("synthesis error: {0}")]
    Synthesis(#[from] ark_relations::r1cs::SynthesisError),

    /// A serialized PK / VK / proof byte blob failed to decode.
    /// Most often a version mismatch or a truncated blob.
    #[error("deserialization error: {0}")]
    Deserialize(#[from] ark_serialize::SerializationError),
}

/// The `Result` type for prover operations.
pub type ProverResult<T> = Result<T, ProverError>;

/// Run Groth16 trusted setup for a circuit.
///
/// `circuit_for_setup` is the circuit instance used to extract
/// the constraint structure. It must be the same circuit *type*
/// real proofs will be generated for, with `Option`-witness slots
/// either populated by dummy values or left as `None` — the
/// arkworks setup path accepts both because it only inspects the
/// constraint graph, not the witness values.
///
/// **Use `Circuit::empty()`** for this argument by convention.
/// Every circuit module ships an `empty()` constructor designed
/// for this exact call site.
///
/// `rng` is the setup randomness. **Use `ark_std::test_rng()`
/// for development.** A production setup needs a real ceremony
/// (Powers of Tau); the random tau lives only briefly in
/// process memory but if it is recovered, every proof for this
/// circuit becomes forgeable.
///
/// Returns `(PK, VK)`. Persist both; the PK gets reused on every
/// prove call, the VK gets deployed to the verifier.
pub fn setup<C, R>(
    circuit_for_setup: C,
    rng: &mut R,
) -> ProverResult<(CircuitProvingKey, CircuitVerifyingKey)>
where
    C: ConstraintSynthesizer<Fq>,
    R: RngCore + CryptoRng,
{
    let (pk, vk) =
        Groth16::<Bn254>::circuit_specific_setup(circuit_for_setup, rng)?;
    Ok((pk, vk))
}

/// Generate a Groth16 proof for a populated circuit instance.
///
/// `circuit` must have every `Option` witness field populated
/// (typically constructed via the circuit's `new(...)`
/// constructor). `pk` is the proving key produced by [`setup`]
/// for this circuit type.
///
/// `rng` is the proving randomness. Unlike setup randomness,
/// this can be any cryptographically-secure RNG; the protocol
/// doesn't pin a specific source. `ark_std::test_rng()` for
/// development, the OS RNG (`OsRng`) for production.
pub fn prove<C, R>(
    circuit: C,
    pk: &CircuitProvingKey,
    rng: &mut R,
) -> ProverResult<CircuitProof>
where
    C: ConstraintSynthesizer<Fq>,
    R: RngCore + CryptoRng,
{
    let proof = Groth16::<Bn254>::prove(pk, circuit, rng)?;
    Ok(proof)
}

/// Verify a Groth16 proof against its verifying key and the
/// public inputs.
///
/// `public_inputs` is the list of `Fq` values the circuit
/// allocated via `new_input(...)`, in the order they were
/// allocated. Each circuit module's docs pin that order; the
/// caller is responsible for matching it.
///
/// **Note on field types.** Groth16's public-input slot is
/// arkworks' BN254 scalar field `Fr` (not the base field `Fq`).
/// For Baby Jubjub-flavoured circuits — where every protocol
/// value lives in `Fq` (BN254's base field, which is also the
/// curve's scalar field for the inner curve) — these are the
/// SAME prime field by the BN254 / Baby Jubjub relationship.
/// This function takes `Fq` inputs (the protocol's
/// public-facing field) and reinterprets them as Groth16's
/// `Fr` internally; the bijection is just byte-equality.
pub fn verify(
    vk: &CircuitVerifyingKey,
    public_inputs: &[Fq],
    proof: &CircuitProof,
) -> ProverResult<bool> {
    // BN254's scalar field Fr (what Groth16 expects for public
    // inputs) is the SAME prime field as BN254's base field Fq
    // for circuits like ours, where the circuit's "field" is the
    // curve's scalar field. The native `crypto::babyjub::Fq` is
    // `ark_bn254::Fr` in arkworks' naming — confusingly.
    //
    // We reinterpret each Fq input as the equivalent Bn254Fr by
    // round-tripping through the BigInt representation. Lossless.
    let inputs_as_bn254_fr: Vec<Bn254Fr> = public_inputs
        .iter()
        .map(|x| Bn254Fr::from_le_bytes_mod_order(&x.into_bigint().to_bytes_le()))
        .collect();

    let prepared_vk: PreparedVerifyingKey<Bn254> = vk.clone().into();
    let accepted =
        Groth16::<Bn254>::verify_with_processed_vk(&prepared_vk, &inputs_as_bn254_fr, proof)?;
    Ok(accepted)
}

/// Serialize a proving key to bytes for persistence. Format is
/// arkworks' compressed canonical encoding — same shape the
/// future `prover-server` writes to `keys/<circuit-name>.pk`.
pub fn serialize_pk(pk: &CircuitProvingKey) -> ProverResult<Vec<u8>> {
    let mut bytes = Vec::new();
    pk.serialize_compressed(&mut bytes)?;
    Ok(bytes)
}

/// Deserialize a proving key from its compressed canonical
/// bytes. Inverse of [`serialize_pk`].
pub fn deserialize_pk(bytes: &[u8]) -> ProverResult<CircuitProvingKey> {
    let pk = CircuitProvingKey::deserialize_compressed(bytes)?;
    Ok(pk)
}

/// Serialize a verifying key to bytes (arkworks' compressed
/// canonical encoding).
///
/// This is the form Sui's `groth16::prepare_verifying_key`
/// accepts on chain (per its docstring: "An Arkworks canonical
/// compressed serialization of a verifying key"). It's also the
/// form the off-chain `prover-server` persists and serves over
/// HTTP — one encoding for both consumers.
pub fn serialize_vk(vk: &CircuitVerifyingKey) -> ProverResult<Vec<u8>> {
    let mut bytes = Vec::new();
    vk.serialize_compressed(&mut bytes)?;
    Ok(bytes)
}

/// Deserialize a verifying key from its compressed canonical
/// bytes. Inverse of [`serialize_vk`].
pub fn deserialize_vk(bytes: &[u8]) -> ProverResult<CircuitVerifyingKey> {
    let vk = CircuitVerifyingKey::deserialize_compressed(bytes)?;
    Ok(vk)
}

/// Serialize a proof to bytes. The on-chain verifier reads this
/// alongside the public inputs.
pub fn serialize_proof(proof: &CircuitProof) -> ProverResult<Vec<u8>> {
    let mut bytes = Vec::new();
    proof.serialize_compressed(&mut bytes)?;
    Ok(bytes)
}

/// Deserialize a proof from its compressed canonical bytes.
pub fn deserialize_proof(bytes: &[u8]) -> ProverResult<CircuitProof> {
    let proof = CircuitProof::deserialize_compressed(bytes)?;
    Ok(proof)
}
