import { describe, expect, it } from "vitest";
import { ed25519, x25519 } from "@noble/curves/ed25519";
import { hkdf } from "@noble/hashes/hkdf";
import { sha256 } from "@noble/hashes/sha256";
import {
  deriveFromDeterministicSigner,
  deriveFromSignature,
  deriveFromWalletSigner,
} from "../derive.js";
import {
  CURRENT_DERIVATION_VERSION,
  DERIVE_SIGNATURE_FEATURE_SCOPE,
  ROOT_SCOPE,
} from "../constants.js";
import { canonicalMessageBytes } from "../message.js";

/**
 * Cross-device stability guarantee.
 *
 * What this test promises (and protects):
 *
 *   For a given wallet identity (signing private key), and a given
 *   canonical message, the derived X25519 *public key* is byte-identical
 *   on every machine — regardless of OS, browser, or which Sui wallet is
 *   producing the signature — provided the wallet is RFC-8032-compliant
 *   for Ed25519 (which any Sui wallet must be).
 *
 * The pinned values below were generated by running this test once with
 * placeholders, capturing the actual output, and writing it back as the
 * golden. Any future change to:
 *
 *   - the canonical-message format (line order, separators, encoding),
 *   - the HKDF salt or info or hash function,
 *   - the X25519 derivation pipeline,
 *
 * will break these assertions. That is the point: if a change to the
 * pipeline silently changed every user's derived key, this test fails
 * loudly before it ships.
 *
 * The test private key is intentionally synthetic. It exists nowhere
 * but in this file, has never been registered, and never will be.
 *
 * Both signing paths (`signPersonalMessage` and `misc:deriveSignature`)
 * share the same HKDF tail, so each path gets its own golden — they
 * are NOT expected to produce the same X25519 keypair (different
 * signature inputs ⇒ different HKDF outputs).
 */

// 32-byte private key: bytes 0x01..0x20. Reproducible everywhere.
const ED25519_PRIVATE_KEY = Uint8Array.from(
  Array.from({ length: 32 }, (_, i) => i + 1),
);

// Pinned Sui-style address. Deliberately not derived from the private
// key above; addresses are part of the canonical message but not part
// of the signing identity, so we want the test to lock in the
// "address-as-message-content" interpretation.
const PINNED_ADDRESS =
  "0x0000000000000000000000000000000000000000000000000000000000000abc";

const CANONICAL_MESSAGE = {
  address: PINNED_ADDRESS,
  version: CURRENT_DERIVATION_VERSION,
  scope: ROOT_SCOPE,
};

// =============================================================================
// Path A — sui:signPersonalMessage (RFC 8032 Ed25519, deterministic)
// =============================================================================

const PATH_A_GOLDEN_X25519_PUBLIC_KEY_HEX =
  "fecf78351c4926c79d6d479c897b5d915e7bcab6ef080cdce836b33a93523a29";

describe("cross-device stability — sui:signPersonalMessage path", () => {
  it("produces the pinned X25519 public key for a fixed identity + message", async () => {
    const messageBytes = canonicalMessageBytes(CANONICAL_MESSAGE);

    // Stand in for any RFC-8032 wallet: sign locally with @noble/curves.
    const signer = async (bytes: Uint8Array) => {
      const signature = ed25519.sign(bytes, ED25519_PRIVATE_KEY);
      return { signature };
    };

    const result = await deriveFromWalletSigner(signer, CANONICAL_MESSAGE);

    expect(Buffer.from(result.encryptionPublicKey).toString("hex")).toBe(
      PATH_A_GOLDEN_X25519_PUBLIC_KEY_HEX,
    );
    // The canonical message hash is also part of the cross-device
    // contract (it's the cache key). Lock it in.
    expect(result.canonicalMessageDigest.length).toBe(32);
    expect(Buffer.from(result.canonicalMessageDigest).toString("hex")).toBe(
      Buffer.from(sha256(messageBytes)).toString("hex"),
    );
  });

  it("is byte-identical across two independent runs (RFC 8032 determinism)", async () => {
    const sign = async (bytes: Uint8Array) => ({
      signature: ed25519.sign(bytes, ED25519_PRIVATE_KEY),
    });
    const a = await deriveFromWalletSigner(sign, CANONICAL_MESSAGE);
    const b = await deriveFromWalletSigner(sign, CANONICAL_MESSAGE);

    expect(Buffer.from(a.encryptionPublicKey).toString("hex")).toBe(
      Buffer.from(b.encryptionPublicKey).toString("hex"),
    );
    expect(Buffer.from(a.encryptionPrivateKey).toString("hex")).toBe(
      Buffer.from(b.encryptionPrivateKey).toString("hex"),
    );
  });

  it("a different canonical message produces a different X25519 public key", async () => {
    const sign = async (bytes: Uint8Array) => ({
      signature: ed25519.sign(bytes, ED25519_PRIVATE_KEY),
    });
    const original = await deriveFromWalletSigner(sign, CANONICAL_MESSAGE);
    const rotated = await deriveFromWalletSigner(sign, {
      ...CANONICAL_MESSAGE,
      version: CURRENT_DERIVATION_VERSION + 1,
    });
    expect(Buffer.from(original.encryptionPublicKey).toString("hex")).not.toBe(
      Buffer.from(rotated.encryptionPublicKey).toString("hex"),
    );
  });
});

// =============================================================================
// Path B — misc:deriveSignature (wallet-internal Ed25519 sub-key)
// =============================================================================

// Synthetic "wallet-internal" signature bytes. In production this would
// be the deterministic output of misc:deriveSignature, where the wallet
// signs its own canonical envelope with an identity-derived sub-key.
// For the golden test we just need a fixed 64-byte signature; the
// derivation pipeline downstream is what we're locking in.
const PATH_B_PINNED_SIGNATURE = Uint8Array.from(
  Array.from({ length: 64 }, (_, i) => 0x80 + (i & 0x7f)),
);

const PATH_B_GOLDEN_X25519_PUBLIC_KEY_HEX =
  "72adc941c9e353d148b9514e280cac1d1b5a84491bc0b7b672cae2d8c731d45c";

describe("cross-device stability — misc:deriveSignature path", () => {
  it("produces the pinned X25519 public key for a fixed signature input", async () => {
    const signer = async (scope: string, _bytes: Uint8Array) => {
      // Real wallets ignore the dApp's bytes (they sign their own envelope)
      // and return a signature derived from (identity, scope). We assert
      // the SDK forwards the configured scope — anything else means the
      // SDK silently rotated the wallet sub-key.
      expect(scope).toBe(DERIVE_SIGNATURE_FEATURE_SCOPE);
      return { signature: PATH_B_PINNED_SIGNATURE };
    };

    const result = await deriveFromDeterministicSigner(
      signer,
      CANONICAL_MESSAGE,
      DERIVE_SIGNATURE_FEATURE_SCOPE,
    );

    expect(Buffer.from(result.encryptionPublicKey).toString("hex")).toBe(
      PATH_B_GOLDEN_X25519_PUBLIC_KEY_HEX,
    );
  });

  it("matches deriveFromSignature called directly with the same bytes", async () => {
    // The deterministic-signer helper is just a thin wrapper over
    // deriveFromSignature once the wallet returns. Lock that equivalence
    // in so future refactors can't drift the two paths apart.
    const direct = deriveFromSignature(PATH_B_PINNED_SIGNATURE, CANONICAL_MESSAGE);
    expect(Buffer.from(direct.encryptionPublicKey).toString("hex")).toBe(
      PATH_B_GOLDEN_X25519_PUBLIC_KEY_HEX,
    );
  });
});

// =============================================================================
// HKDF-pipeline integrity — independent reconstruction of Path A
// =============================================================================

describe("HKDF pipeline integrity", () => {
  it("derived key matches an independent HKDF + x25519 implementation", async () => {
    // We re-do the derivation by hand using the documented spec:
    //   ikm  = signature_bytes
    //   salt = "whisper/v1/encryption-keypair"
    //   info = "x25519"
    //   seed = HKDF-SHA256(ikm, salt, info, 32)
    //   pub  = X25519.scalarMultBase(seed)
    //
    // If this test fails, either the spec drifted from the
    // implementation or the implementation drifted from the spec.
    // Either way it's a bug that would break every existing user's keys.
    const sig = ed25519.sign(
      canonicalMessageBytes(CANONICAL_MESSAGE),
      ED25519_PRIVATE_KEY,
    );

    const seed = hkdf(
      sha256,
      sig,
      new TextEncoder().encode("whisper/v1/encryption-keypair"),
      new TextEncoder().encode("x25519"),
      32,
    );
    const pubByHand = x25519.getPublicKey(seed);

    const viaSdk = await deriveFromWalletSigner(
      async (bytes) => ({ signature: ed25519.sign(bytes, ED25519_PRIVATE_KEY) }),
      CANONICAL_MESSAGE,
    );

    expect(Buffer.from(viaSdk.encryptionPublicKey).toString("hex")).toBe(
      Buffer.from(pubByHand).toString("hex"),
    );
  });
});
